development:
  adapter: postgresql
  username: vincent
  password: vincent
  host: localhost
  database: dbvincentmyapp
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  username: vincent
  password: vincent
  host: localhost
  database: dbvincentmyapp
  pool: 5
  timeout: 5000
